version: "3.9"

services:
  slides_bot:
    build: .
    container_name: slides_bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/data
      - ./templates:/app/media/templates
      - ./logs:/app/logs
      - ./temp:/app/media/temp
      - ./fonts:/usr/share/fonts/custom:ro
